### PR TITLE
Fix memory and swap

### PR DESCRIPTION
**Pull request by Nicolas01**
For the memory, I remove the option « -to » which doesn't exist, and I simplified the retrieving of the memory info.  
For the swap, I used « free -t » to retrieve the swap info.  
For teh CPU, I added « BogoMIPS » in addition to « bogomips ».

### CODE REVIEW

**Comment by Nicolas01** [comment]
Those instructions works well on Archlinux:
```
/usr/bin/free | grep Mem: | awk '{print $4+$6+$7}' 
/usr/bin/free | grep Mem: | awk '{print $2}'
```
But I am not sure that the columns of your output match mines.
Here is my output of /usr/bin/free:
```
              total       utilisé      libre     partagé tamp/cache   disponible
Mem:        2070188      190652      224440       41828     1655096     1812208
Partition d'échange:           0           0           0
```
As you see, it's in french, but it doesn't matter.
Column 3 (utilisé) is used memory and column 7 (disponible) is available memory (so I don't need to sum columns to have it).

About the swap, with the command `/usr/bin/free | sed -n '3p' | awk '{print $5}'`
I get the line 3 (I can't filter with the Swap keyword because my output is not in english), then I get the column 5. Actually 'Partition d'échange:' takes 2 columns while 'Swap:' should only take 1. That may be why this command doesn't work on your system, but this is more a language problem than a system problem.

A solution could be to prefix all the commands by `LC_ALL=C` to get the output in english:
```
LC_ALL=C /usr/bin/free | grep Swap: | awk '{print $2}'
```

**Comment by shevabam** [comment]
Argh, the `free` output on Arch is not at all like Debian for example...
On Debian, we have:

                 total       used       free     shared    buffers     cached
    Mem:        379748     122560     257188          0      13460      55348
    -/+ buffers/cache:      53752     325996
    Swap:       180220          0     180220

So in the script for the available memory, I do the sum of free+buffers+cached ($4+$6+$7) but the columns are not the same on Arch...

So the method via the free command must be changed :(

Can you send me the output of `cat /proc/meminfo` on Arch please?

About the swap, I thought it was the same for all languages (I'm French too ^^).
Given the problem with the free command, I'll keep the current process (`grep SwapFree /proc/meminfo | awk '{print $2}'`).

Thank you for the information ;)

**Comment by vampirexhunter** [comment]
Free
[code]
              total        used        free      shared  buff/cache   available
Mem:         250936       31988       52088         412      166860      200644
Swap:       1048572           0     1048572
[/code]
cat /proc/meminfo
[code]
MemTotal:         250936 kB
MemFree:           52268 kB
MemAvailable:     200636 kB
Buffers:           23892 kB
Cached:           112240 kB
SwapCached:            0 kB
Active:           107784 kB
Inactive:          40280 kB
Active(anon):       5752 kB
Inactive(anon):    11080 kB
Active(file):     102032 kB
Inactive(file):    29200 kB
Unevictable:       13520 kB
Mlocked:           13520 kB
SwapTotal:       1048572 kB
SwapFree:        1048572 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         25468 kB
Mapped:            67640 kB
Shmem:               412 kB
Slab:              30544 kB
SReclaimable:      24636 kB
SUnreclaim:         5908 kB
KernelStack:         808 kB
PageTables:         1272 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1174040 kB
Committed_AS:     278820 kB
VmallocTotal:     761856 kB
VmallocUsed:        5596 kB
VmallocChunk:     730636 kB
[/code]

**Comment by shevabam** [comment]
Thanks @vampirexhunter ;)

I made some changes on memory.php file. Can you test it please ?

**Comment by vampirexhunter** [comment]
Thank you, it works :)

**Comment by shevabam** [comment]
Fixed on v2.4

**Pull request closed without merging**
